# Generated by Django 2.2.6 on 2019-11-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20191103_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
