# Generated by Django 2.2.6 on 2019-11-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
